from typing import TypeVar

from .core import AgnosticDatabase, AgnosticCollection, AgnosticClient

T = TypeVar('T')

def create_asyncio_class(cls: T) -> T: ...

class AsyncIOMotorClient(AgnosticClient): ...
class AsyncIOMotorDatabase(AgnosticDatabase): ...
class AsyncIOMotorCollection(AgnosticCollection): ...
